---
title: "UMAP"
author: "Diogo Esteves"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
setwd("C:/Users/dases/Desktop/Projeto") # isto é muito importante definir antes - ficheiros muito grandes

```

## Installing Libraries/packages/dependencies

```{r}

#Bioconductor
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()
BiocManager::install(c("SingleCellExperiment", "GenomeInfoDb", "SummarizedExperiment", "DelayedArray", "HDF5Array", "BiocParallel", "SRAdb"))

#Monocle 3, usando o pacote devtools
if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("cole-trapnell-lab/monocle3", ref="master")

```
## Loading Libraries
```{r}
# Carregar as bibliotecas após a instalação
library(Seurat)
library(monocle3)
library(R.utils)
library(ggplot2)
library(dplyr)
library(SRAdb)
library(RSQLite)
library(graph)
library(RCurl)
library(GEOquery)
```


## Data Import
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE202639

```{r}
# Define as variáveis de acesso a db
url_sra <- "https://gbnci.cancer.gov/backup/SRAmetadb.sqlite.gz"
localfile <- "SRAmetadb.sqlite.gz"

# Verifica se o arquivo já existe antes de fazer o download
if (!file.exists(localfile)) {
  download.file(url_sra, destfile = localfile, mode = "wb", timeout = 900)
}

# o próximo passo descompacta o arquivo se necessário, passo muito demorado e sem barra de progresso... ter em atenção se executou corretamente, ou se ainda está a ser executado em segundo plano, mesmo se abortarem o processo...

if (!file.exists("SRAmetadb.sqlite") && file.exists(localfile)) {
  gunzip(localfile, overwrite = TRUE, BFR.SIZE = 1e+07) #tive de redefinir o parametro BFR.SIZE para lidar com este ficheiro
}

# Verifica o tamanho do arquivo descompactado
file.info("SRAmetadb.sqlite")$size

# Inicializa a conexão
if (file.exists("SRAmetadb.sqlite")) {
  sra_con <- dbConnect(RSQLite::SQLite(), "SRAmetadb.sqlite", synchronous = NULL)
  dbListTables(sra_con)
} else {
  print("O arquivo descompactado não existe ou é inválido.")
}

```
 
## Preprocessing
```{r}
```


## Analysis

```{r}
# Setup Monocle
sc_data <- setup_cds(sc_data, method = "UMAP")

# Trajectory analysis
sc_data <- reduce_dimension(sc_data)
plot_cells(sc_data, color_by = "your_cell_type_variable")
```

## Differential Expression Analysis

```{r}
# Differential expression
diff_exp_results <- differentialGeneTest(sc_data[cell_ids,], fullModelFormulaStr = "~ condition")
head(diff_exp_results)
```

## Visualization


```{r}
# Run UMAP
sc_data <- runUMAP(sc_data, dims = 1:20)

# Visualization
DimPlot(sc_data, reduction = "umap", group.by = "condition")
```

```{r}
```